### PR TITLE
[Iris] Add suggestions for intro discussion

### PR DESCRIPTION
**Pull request by dkillick**
Adds three bullet points that help inform the discussion about Iris that forms the very start of the course.

### CODE REVIEW

**Comment by dkillick** [comment]
@pp-mo @pelson @lbdreyer any thoughts on this (small) change?

**Comment by lbdreyer** [comment]
Why do these questions need to be written down in the course? They seem more like a prompt to the teacher to me

**Comment by dkillick** [comment]
@lbdreyer I definitely see this addition as being in the learner space and not the teacher space. Much like with the ill-defined NumPy course exercises, I think this interactive section of the Iris course could be improved for the learners if they have a clear idea of the sort of topics they could be discussing.

**Comment by pelson** [comment]
Personally, I'd remove the **discuss** section altogether. We have a bit of a problem with these courses in that they are open source material that can be used online by anybody, yet they are also the material that we use in the classroom. These are two very different learning environments, and need very different approaches. I don't really have a solution to that, but can see why as a group, we regularly disagree on the type of content that belongs in here.

**Comment by dkillick** [comment]
Based on the quite pertinent comments that @lbdreyer and @pelson have made on this suggestion, I've elected to remove the "Discuss" cell entirely. We can always add this particular content in without a cell to support it.

**Comment by dkillick** [comment]
Self-merging based on approval from @corinnebosley.

**Pull request merged**
