### PR TITLE
Improvements to the Iris course

### PR DESCRIPTION
**Pull request by dkillick**
A selection of improvements for the Iris course, including:

* improvements to the wording so that the course works better as a read resource as well as a taught resource, and
* updating some of the course content.

Changes to the course content include:

 * a (short!) new section on concatenate,
 * a (short!) new element on slices_over in the Iteration section,
 * removing the element on old-style time constraints from the constrained loading section (it doesn't work on Iris 1.8!), and
 * changing the subset cube plotted in the plotting section so that it plots time against latitude for a fixed longitude and so makes a more intuitive plot.

### CODE REVIEW

**Comment by pelson** [comment]
The concatenate section depends on indexing, which has not yet been introduced... I will take a look at alternatives after merging.

**Comment by dkillick** [comment]
I thought that too, but it is such a tiny usage that I figured it wouldn't be too bad and could instead be used as a sneak peek at what's coming.

**Comment by pelson** [comment]
> a (short!) new element on slices_over in the Iteration section,

This section starts with a negative (e.g. "what slices is not helpful for...") and I tend to prefer the prose to be more positive - e.g. in some situations we want to...

**Comment by dkillick** [comment]
> This section starts with a negative

Hmm... one of the technical authoring principles is "be positive", which I failed to do here :unamused: I seem to remember I had a couple of goes at making it positive too.

**Comment by pelson** [comment]
> changing the subset cube plotted in the plotting section so that it plots time against latitude for a fixed longitude and so makes a more intuitive plot.

I'm not keen. I think we probably need to address the underlying issue (iris and the mpl version), not the course.

**Comment by dkillick** [comment]
> I think we probably need to address the underlying issue

I still think the underlying issue is the data!

**Comment by pelson** [comment]
> I still think the underlying issue is the data!

Oh I see. You're fixing the stripe?

**Comment by dkillick** [comment]
> You're fixing the stripe?

Yeah - I thought that was the problem you were meaning. If it isn't, what is the problem you were meaning?

**Comment by pelson** [comment]
> If it isn't, what is the problem you were meaning?

The ugly date axis...

**Comment by pelson** [comment]
I quite like the stripe - it is a nice feeling when people start talking about the data, and forget how easy it was to look at the data :smile:

**Comment by dkillick** [comment]
> The ugly date axis

Oh, I think I'd written that off as being in the just not going to be solved soon camp...

> it is a nice feeling when people start talking about the data

Sounds like a good reason to revert that particular change then :smile:

**Comment by dkillick** [comment]
The above commit shortens long lines so that they don't overflow off the right of the screen when presenting this course.

**Comment by dkillick** [comment]
Improvements added, rebased onto latest master. Still need to check that some sort of action has been taken on all of the comments above, however.

**Comment by dkillick** [comment]
Here's a summary of @pelson's review comments above:

 1. New concatenate section depends on indexing a cube, which hasn't been introduced in the course by that point.
 2. New slices_over section starts with a negative statement.
 3. Changing the plot that shows an odd stripe in the plotted data

**Comment by dkillick** [comment]
> 1. New concatenate section depends on indexing a cube, which hasn't been introduced in the course by that point.

This remains an issue, as I don't think there are any two datasets in the sample data that can be concatenated. Therefore a simple approach to producing some data that can be concatenated is to index an existing cube into two smaller sections. Alternatives:
 * Construct two cubes by hand that can be concatenated. Not desirable as it would introduce unnecessary code into the course content.
 * Move the indexing section to just above the merge section. The indexing section does not rely on anything introduced between its current location and its proposed new location earlier in the course. (For ref, the section between the end of saving and its current location are: _Merging_, _Identifying merge problems_, _Exercise 4_, _Concatenate_, _Load Callbacks_.)

**Comment by dkillick** [comment]
> 2\. New slices_over section starts with a negative statement.

I've reworded the start of this section so that it has a positive tone.

> 3\. Changing the plot that shows an odd stripe in the plotted data.

I've reverted this change so that the odd stripe is retained.

**Comment by dkillick** [comment]
I've made changes based on the comments above. I've also removed a load of seemingly spurious  boldface emphasis from code cells, as I think it may be unnecessary.

**Comment by pelson** [comment]
> I've made changes based on the comments above.

The outputs have been removed. This makes the course material hard to look at without running the notebooks, and will prevent you being able to print them out...

**Comment by pelson** [comment]
We desperately need to be able to review this easily. I suspect it would help to split the course into several notebooks...

**Comment by dkillick** [comment]
Having backed out the clear code cell output commit I think this is ready now. I'm going to defer splitting the course into several notebooks until we have a little time to think about this a bit more.

@pelson any chance you can do the honours? Turns out I don't have write access to this repo :expressionless:

**Pull request merged**
