### PR TITLE
[dask] Updates to "Iris Load with dask" section

### PR DESCRIPTION
**Pull request by dkillick**
Ignoring the noise of the notebook diff, this PR makes the review changes suggested to #107. These are a few minor changes to some bits of text and code content. This PR does _not_ address the more complex questions about [ordering of content](https://github.com/SciTools/courses/pull/107#pullrequestreview-100121064) or [delaying the merge operation](https://github.com/SciTools/courses/pull/107#pullrequestreview-101003572).

### CODE REVIEW

**Comment by pp-mo** [comment]
Checked coverage of comments on previous -- all good, + this fixes all :+1:
Todo : review overall, coming up ...

**Comment by pp-mo** [comment]
Nice work @dkillick LGTM

**Comment by pp-mo** [comment]
I think ["that comment"](https://github.com/SciTools/courses/pull/107#discussion_r172046448) is still outstanding though :  
To reiterate : what does delaying a merge achieve; is this is good example or is it confusing; can we modify this to show something with real performance benefit ?

**Comment by dkillick** [comment]
@pp-mo IMO this contentious bit is a nice example of adding arbitrary processing to the task graph using `delayed`. Not everything we show needs to be there purely for efficiency reasons – in fact, we already know that in common use-cases _none_ of the examples here make Iris any faster. What we want to do is teach people how they can use dask with Iris, and I still think that this section has value in demonstrating how to add arbitrary Iris processing to a task graph. In this case you can defer the entire process of files --> bag --> cubelist --> single merged cube, which I think has benefit.

We could make it more clear that this is offered as an example of using delayed, by modifying the last sentence here to say something like:

```
This is an example of using `delayed` to integrate arbitrary Iris processing into our task graph:
```

**Comment by kaedonkers** [comment]
@pp-mo I second @dkillick's opinion. The current example is good for demonstrating how to add an arbitrary process to a task graph (even if in this case there is no performance benefit). I see this section of the workbook much more about introducing the user how to use dask with iris in as clear a manner as possible.
Something which needs to be considered later are examples of dask+iris patterns which **do** add performance benefits, something I was not able to tackle with this addition to the notebook.

**Pull request merged**
