### PR TITLE
replaced pointless question with statement

### PR DESCRIPTION
**Pull request by corinnebosley**
This was a bit of a non-question anyway, and I intend to add another few questions later on in the course, so I just took this one out.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@djkirkham @pp-mo @dkillick I think I am going to have problems with this.  I based it off my last PR (https://github.com/SciTools/courses/pull/45) so that I wasn't blocked by waiting for it to be merged, and I don't think it's really done what I want it to do.  

Never mind, I will cross that bridge when I come to it.

**Comment by djkirkham** [comment]
Once #45 is merged you can use `rebase --onto #46 #45 upstream/master` (where `#46` and `#46`) are replaced with the names of your branches for those PRs

**Comment by pp-mo** [comment]
On reflection, I don't much like this proposal so much.
I think there was a point here in getting the user to the start looking at the matplotlb documentation.
Whether this is the right point to do that, or the right lookup to suggest, is probably another question...

discussed offline with @corinnebosley 
 * possibly the exercise here should stay, but needs to be fit-for-purpose
 * We think at the least, we ***should*** have the user look at "gca" *before* "gcf", as the documentation of the latter is now so short as to be pointless.

The decision on this really relates to what we think these notebooks are "for", e.g.
 * self-learning workbook
 * supervised workshop
 * readable account
 * worksheet material for more traditional teaching / lecture

When we have a more solid idea of purpose + intended format, we can review this issue with some idea of what to aim for in this particular detail.
@marqh @dkillick we should discuss the general point offline tomorrow

**Comment by marqh** [comment]
there are useful thoughts in here, but I don't think we are going to adopt it as it is.
It has developed merge conflicts now

@corinnebosley if you have a key change you'd like included from here, please may you raise it as separate PR?

i'm going to close this one now

**Pull request closed without merging**
