### PR TITLE
add posters directory with mpl poster inside

### PR DESCRIPTION
**Pull request by corinnebosley**
Made a top-level directory called 'posters' and put a poster outlining matplotlib elements inside it.

### CODE REVIEW

**Comment by corinnebosley** [comment]
@dkillick Ping!

**Comment by corinnebosley** [comment]
@dkillick Ping! 

I quite like the extra border.

**Comment by corinnebosley** [comment]
@dkillick Ping!

**Comment by dkillick** [comment]
LGTM (Link Good The Master [file]) 😉

**Comment by dkillick** [comment]
@corinnebosley this is a great poster 👍 Unfortunately the original (editable) file used to produce this poster has been lost, but I'm going to merge this anyway. A salutary lesson in only exporting a file and not saving the original...

**Pull request merged**
